version: '3.1'

services:
  db:
    container_name: section_3_dia_1
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  default:
    name: section_3_dia_1